export const ADD_CAN_REQUEST = '@cans/ADD_CAN_REQUEST';
export const ADD_CAN_SUCCESS = '@cans/ADD_CAN_SUCCESS';
export const ADD_CAN_FAILURE = '@cans/ADD_CAN_FAILURE';
export const CANS_FILTER_CHANGE = '@cans/CANS_FILTER_CHANGE';
export const RECEIVE_FILTERED_CANS = '@cans/RECEIVE_FILTERED_CANS';
export const FETCH_CANS_REQUEST = '@cans/FETCH_CANS_REQUEST';
export const FETCH_CANS_FAILURE = '@cans/FETCH_CANS_FAILURE';
export const FETCH_CANS_SUCCESS = '@cans/FETCH_CANS_SUCCESS';

export const RECEIVE_CANS = '@cans/RECEIVE_CANS';
export const REMOVE_CAN_REQUEST = '@cans/REMOVE_CAN_REQUEST';
export const REMOVE_CAN_SUCCESS = '@cans/REMOVE_CAN_SUCCESS';
export const REMOVE_CAN_FAILURE = '@cans/REMOVE_CAN_FAILURE';

export const UPDATE_CAN_REQUEST = '@cans/UPDATE_CAN_REQUEST';
export const UPDATE_CAN_SUCCESS = '@cans/UPDATE_CAN_SUCCESS';
export const UPDATE_CAN_FAILURE = '@cans/UPDATE_CAN_FAILURE';

export const UNSET_ACTIVE_CAN = '@cans/UNSET_ACTIVE_CAN';
export const FETCH_TRANSACTIONS_REQUEST = '@cans/FETCH_TRANSACTIONS_REQUEST';
export const FETCH_TRANSACTIONS_FAILURE = '@cans/FETCH_TRANSACTIONS_FAILURE';
export const FETCH_TRANSACTIONS_SUCCESS = '@cans/FETCH_TRANSACTIONS_SUCCESS';

export const EXPORT_CANS_AGING_REQUEST = '@cans/EXPORT_CANS_AGING_REQUEST';
export const EXPORT_CANS_AGING_SUCCESS = '@cans/EXPORT_CANS_AGING_SUCCESS';
export const EXPORT_CANS_AGING_FAILURE = '@cans/EXPORT_CANS_AGING_FAILURE';
export const EXPORT_CANS_REQUEST = '@cans/EXPORT_CANS_REQUEST';
export const EXPORT_CANS_SUCCESS = '@cans/EXPORT_CANS_SUCCESS';
export const EXPORT_CANS_FAILURE = '@cans/EXPORT_CANS_FAILURE';

export const IMPORT_CANS_REQUEST = '@cans/IMPORT_CANS_REQUEST';
export const IMPORT_CANS_SUCCESS = '@cans/IMPORT_CANS_SUCCESS';
export const IMPORT_CANS_FAILURE = '@cans/IMPORT_CANS_FAILURE';

export const FETCH_CAN_REQUEST = '@cans/FETCH_CAN_REQUEST';
export const FETCH_CAN_SUCCESS = '@cans/FETCH_CAN_SUCCESS';
export const FETCH_CAN_FAILURE = '@cans/FETCH_CAN_FAILURE';
export const RECEIVE_CAN = '@cans/RECEIVE_CAN';

export const TRANSFER_CAN_REQUEST = '@cans/TRANSFER_CAN_REQUEST';
export const TRANSFER_CAN_SUCCESS = '@cans/TRANSFER_CAN_SUCCESS';
export const TRANSFER_CAN_FAILURE = '@cans/TRANSFER_CAN_FAILURE';

export const PICKUP_CAN_REQUEST = '@cans/PICKUP_CAN_REQUEST';
export const PICKUP_CAN_SUCCESS = '@cans/PICKUP_CAN_SUCCESS';
export const PICKUP_CAN_FAILURE = '@cans/PICKUP_CAN_FAILURE';
export const CREATE_CAN_NOTE_REQUEST = '@cans/CREATE_CAN_NOTE_REQUEST';
export const CREATE_CAN_NOTE_SUCCESS = '@cans/CREATE_CAN_NOTE_SUCCESS';
export const CREATE_CAN_NOTE_FAILURE = '@cans/CREATE_CAN_NOTE_FAILURE';

export const MOVE_CAN_REQUEST = '@cans/MOVE_CAN_REQUEST';
export const MOVE_CAN_SUCCESS = '@cans/MOVE_CAN_SUCCESS';
export const MOVE_CAN_FAILURE = '@cans/MOVE_CAN_FAILURE';
export const DROPOFF_CAN_REQUEST = '@cans/DROPOFF_CAN_REQUEST';
export const DROPOFF_CAN_SUCCESS = '@cans/DROPOFF_CAN_SUCCESS';
export const DROPOFF_CAN_FAILURE = '@cans/DROPOFF_CAN_FAILURE';
export const RESET_REFRESH_CANS = '@cans/RESET_REFRESH_CANS';
