/* eslint-disable */
export const CURRENT_INVENTORY = [
  {
    location1: {
      id: 1060440,
      name: '6191 West Plymouth Drive, Littleton, CO, 80128',
      description: null,
      type: 'LOCATION',
      waypointType: null,
      waypointName: null,
      location: 'Object',
      createdBy: 'smoore',
      createdDate: '2019-08-19T22:36:59.595Z',
      modifiedBy: null,
      modifiedDate: '2019-08-19T22:36:59.595Z',
    },
    location2: {
      id: null,
      name: null,
      description: null,
      type: null,
      waypointType: null,
      waypointName: null,
      location: 'Object',
      createdBy: null,
      createdDate: null,
      modifiedBy: null,
      modifiedDate: null,
    },
    driver: {
      truck: 'Object',
      id: null,
      name: null,
      username: null,
      photo: null,
      createdBy: null,
      createdDate: null,
      modifiedBy: null,
      modifiedDate: null,
      deleted: null,
    },
    id: 200974,
    documentId: null,
    templateId: 1,
    trackingDocId: null,
    status: 'UNASSIGNED',
    action: 'SPOT',
    size: '30',
    material: 'C & D',
    scheduledDate: '2019-09-06',
    scheduledStart: null,
    scheduledEnd: null,
    poNumber: null,
    contactName: 'Tony',
    contactNumber: '303-517-6635',
    customerName: 'Columbine Knolls HOA',
    instructions: 'Must COW Tony 303-517-6635 placement directions',
    alleyPlacement: 0,
    earlyPickUp: 0,
    okToRoll: 0,
    negotiatedFill: 0,
    cow: 1,
    sos: 0,
    cabOver: 0,
    permittedCan: 0,
    permitNumber: null,
    textOnWay: '+13035176635',
    profileNumber: null,
    signatureRequired: 0,
    customerProvidedProfile: 0,
    priority: 0,
    step: null,
    canId: null,
    createdBy: 'smoore',
    createdDate: '2019-08-19T22:37:01.133Z',
    modifiedBy: null,
    modifiedDate: '2019-08-19T22:37:01.133Z',
    deleted: 0,
    index: 0,
  },
  {
    location1: 'Object',
    location2: 'Object',
    driver: 'Object',
    id: 200284,
    documentId: null,
    templateId: 1,
    trackingDocId: null,
    status: 'UNASSIGNED',
    action: 'SPOT',
    size: '30',
    material: 'C & D',
    scheduledDate: '2019-09-06',
    scheduledStart: null,
    scheduledEnd: null,
    poNumber: null,
    contactName: 'Patricia',
    contactNumber: '404-479-7495',
    customerName: 'EMG LLC',
    instructions:
      'COW  Patricia 404-479-7495.   Best Buy #0694\r\nPlace the dumpster in any parking space close to the docks in the back. If there are any issues, please call Patricia 404-479-7495.',
    alleyPlacement: 0,
    earlyPickUp: 0,
    okToRoll: 0,
    negotiatedFill: 0,
    cow: 1,
    sos: 0,
    cabOver: 0,
    permittedCan: 0,
    permitNumber: null,
    textOnWay: '+14044797495',
    profileNumber: null,
    signatureRequired: 0,
    customerProvidedProfile: 0,
    priority: 0,
    step: null,
    canId: null,
    createdBy: 'smoore',
    createdDate: '2019-08-16T15:09:15.947Z',
    modifiedBy: null,
    modifiedDate: '2019-08-16T15:09:15.947Z',
    deleted: 0,
    index: 0,
  },
  {
    location1: 'Object',
    location2: 'Object',
    driver: 'Object',
    id: 202461,
    documentId: null,
    templateId: 1,
    trackingDocId: null,
    status: 'UNASSIGNED',
    action: 'SPOT',
    size: '30',
    material: 'C & D',
    scheduledDate: '2019-09-06',
    scheduledStart: '08:00:00',
    scheduledEnd: '10:00:00',
    poNumber: null,
    contactName: 'Joel',
    contactNumber: '404-876-7993',
    customerName: 'EMG LLC',
    instructions:
      'Must Call Joel at 404-876-7993 at time of delivery for assistance in placement\r\nGoing to Walgreens, must be after 8:00 am',
    alleyPlacement: 0,
    earlyPickUp: 0,
    okToRoll: 0,
    negotiatedFill: 0,
    cow: 1,
    sos: 0,
    cabOver: 0,
    permittedCan: 0,
    permitNumber: null,
    textOnWay: '+14048767993',
    profileNumber: null,
    signatureRequired: 0,
    customerProvidedProfile: 0,
    priority: 0,
    step: null,
    canId: null,
    createdBy: 'smoore',
    createdDate: '2019-08-26T15:57:14.244Z',
    modifiedBy: null,
    modifiedDate: '2019-08-26T15:57:14.244Z',
    deleted: 0,
    index: 0,
  },
  {
    location1: 'Object',
    location2: 'Object',
    driver: 'Object',
    id: 202823,
    documentId: null,
    templateId: 1,
    trackingDocId: null,
    status: 'UNASSIGNED',
    action: 'SPOT',
    size: '20',
    material: 'C & D',
    scheduledDate: '2019-09-04',
    scheduledStart: null,
    scheduledEnd: null,
    poNumber: null,
    contactName: null,
    contactNumber: null,
    customerName: 'Gelfling, Kira',
    instructions: null,
    alleyPlacement: 0,
    earlyPickUp: 0,
    okToRoll: 0,
    negotiatedFill: 0,
    cow: 0,
    sos: 0,
    cabOver: 0,
    permittedCan: 0,
    permitNumber: null,
    textOnWay: null,
    profileNumber: null,
    signatureRequired: 0,
    customerProvidedProfile: 0,
    priority: 0,
    step: null,
    canId: null,
    createdBy: 'admin-test',
    createdDate: '2019-09-03T21:32:44.942Z',
    modifiedBy: null,
    modifiedDate: '2019-09-03T21:32:44.942Z',
    deleted: 0,
    index: 0,
  },
  {
    location1: 'Object',
    location2: 'Object',
    driver: 'Object',
    id: 202824,
    documentId: null,
    templateId: 1,
    trackingDocId: null,
    status: 'CANCELED',
    action: 'SPOT',
    size: '10',
    material: 'C & D',
    scheduledDate: '2019-09-04',
    scheduledStart: null,
    scheduledEnd: null,
    poNumber: null,
    contactName: null,
    contactNumber: null,
    customerName: 'Seavey, Rob',
    instructions: null,
    alleyPlacement: 0,
    earlyPickUp: 0,
    okToRoll: 0,
    negotiatedFill: 0,
    cow: 0,
    sos: 0,
    cabOver: 0,
    permittedCan: 0,
    permitNumber: null,
    textOnWay: null,
    profileNumber: null,
    signatureRequired: 0,
    customerProvidedProfile: 0,
    priority: 0,
    step: null,
    canId: null,
    createdBy: 'admin-test',
    createdDate: '2019-09-04T14:33:30.373Z',
    modifiedBy: 'admin-test',
    modifiedDate: '2019-09-04T14:35:35.633Z',
    deleted: 0,
    index: 0,
  },
  {
    location1: 'Object',
    location2: 'Object',
    driver: 'Object',
    id: 202595,
    documentId: null,
    templateId: 1,
    trackingDocId: null,
    status: 'UNASSIGNED',
    action: 'SPOT',
    size: '12',
    material: 'C & D',
    scheduledDate: '2019-09-04',
    scheduledStart: null,
    scheduledEnd: null,
    poNumber: null,
    contactName: 'Alex',
    contactNumber: '303-594-4062',
    customerName: 'Encore Homes',
    instructions: '303-594-4062  Alex place in driveway on plywood',
    alleyPlacement: 0,
    earlyPickUp: 0,
    okToRoll: 0,
    negotiatedFill: 0,
    cow: 1,
    sos: 0,
    cabOver: 0,
    permittedCan: 0,
    permitNumber: null,
    textOnWay: '+13035944062',
    profileNumber: null,
    signatureRequired: 0,
    customerProvidedProfile: 0,
    priority: 0,
    step: null,
    canId: null,
    createdBy: 'smoore',
    createdDate: '2019-08-26T20:25:34.150Z',
    modifiedBy: null,
    modifiedDate: '2019-08-26T20:25:34.150Z',
    deleted: 0,
    index: 0,
  },
];

export const WORK_ORDERS = [
  {
    location1: {
      id: 847251,
      name: '13862 West Tufts Avenue, Morrison, CO, 80465',
      description: null,
      type: 'LOCATION',
      waypointType: null,
      waypointName: null,
      location: 'Object',
      createdBy: 'smoore',
      createdDate: '2019-04-05T16:36:01.751Z',
      modifiedBy: null,
      modifiedDate: '2019-04-05T16:36:01.751Z',
    },
    location2: {
      id: null,
      name: null,
      description: null,
      type: null,
      waypointType: null,
      waypointName: null,
      location: 'Object',
      createdBy: null,
      createdDate: null,
      modifiedBy: null,
      modifiedDate: null,
    },
    driver: {
      truck: 'Object',
      id: null,
      name: null,
      username: null,
      photo: null,
      createdBy: null,
      createdDate: null,
      modifiedBy: null,
      modifiedDate: null,
      deleted: null,
    },
    id: 201473,
    documentId: null,
    templateId: 1,
    trackingDocId: null,
    status: 'UNASSIGNED',
    action: 'FINAL',
    size: '30',
    material: 'C & D',
    scheduledDate: '2019-09-07',
    scheduledStart: null,
    scheduledEnd: null,
    poNumber: null,
    contactName: 'Derek',
    contactNumber: '720-203-0704',
    customerName: 'Merica, Derek',
    instructions: null,
    alleyPlacement: 0,
    earlyPickUp: 0,
    okToRoll: 0,
    negotiatedFill: 0,
    cow: 1,
    sos: 0,
    cabOver: 0,
    permittedCan: 0,
    permitNumber: null,
    textOnWay: '+17202030704',
    profileNumber: null,
    signatureRequired: 0,
    customerProvidedProfile: 0,
    priority: 0,
    step: null,
    canId: null,
    createdBy: 'smoore',
    createdDate: '2019-08-21T16:22:56.718Z',
    modifiedBy: null,
    modifiedDate: '2019-08-21T16:22:56.718Z',
    deleted: 0,
    index: 0,
  },
  {
    location1: {
      id: 1060435,
      name: '1819 South Salida Circle, Aurora, CO, 80017',
      description: null,
      type: 'LOCATION',
      waypointType: null,
      waypointName: null,
      location: {
        lon: -104.7850262,
        lat: 39.683271,
      },
      createdBy: 'smoore',
      createdDate: '2019-08-19T22:30:04.251Z',
      modifiedBy: null,
      modifiedDate: '2019-08-19T22:30:04.251Z',
    },
    location2: {
      id: null,
      name: null,
      description: null,
      type: null,
      waypointType: null,
      waypointName: null,
      location: {
        lon: null,
        lat: null,
      },
      createdBy: null,
      createdDate: null,
      modifiedBy: null,
      modifiedDate: null,
    },
    driver: 'Object',
    id: 200973,
    documentId: null,
    templateId: 1,
    trackingDocId: null,
    status: 'UNASSIGNED',
    action: 'FINAL',
    size: '30',
    material: 'C & D',
    scheduledDate: '2019-09-06',
    scheduledStart: null,
    scheduledEnd: null,
    poNumber: null,
    contactName: 'Catherine',
    contactNumber: '720-329-3688',
    customerName: 'Armijo, Catherine',
    instructions: null,
    alleyPlacement: 0,
    earlyPickUp: 0,
    okToRoll: 0,
    negotiatedFill: 0,
    cow: 1,
    sos: 0,
    cabOver: 0,
    permittedCan: 0,
    permitNumber: null,
    textOnWay: '+17203293688',
    profileNumber: null,
    signatureRequired: 0,
    customerProvidedProfile: 0,
    priority: 0,
    step: null,
    canId: null,
    createdBy: 'smoore',
    createdDate: '2019-08-19T22:30:07.503Z',
    modifiedBy: null,
    modifiedDate: '2019-08-19T22:30:07.503Z',
    deleted: 0,
    index: 0,
  },
  {
    location1: {
      id: 980382,
      name: '3151 South Albion Street, Denver, CO, 80222',
      description: null,
      type: 'LOCATION',
      waypointType: null,
      waypointName: null,
      location: {
        lon: -104.9400489,
        lat: 39.6591121,
      },
      createdBy: 'alycia.hilzer@5280waste.com',
      createdDate: '2019-07-01T14:08:15.977Z',
      modifiedBy: null,
      modifiedDate: '2019-07-01T14:08:15.977Z',
    },
    location2: 'Object',
    driver: 'Object',
    id: 201523,
    documentId: null,
    templateId: 1,
    trackingDocId: null,
    status: 'UNASSIGNED',
    action: 'FINAL',
    size: '12',
    material: 'C & D',
    scheduledDate: '2019-09-06',
    scheduledStart: null,
    scheduledEnd: null,
    poNumber: null,
    contactName: 'Bernie',
    contactNumber: '719-989-8061',
    customerName: 'Patrick Chiappetta',
    instructions: '719-989-8061  Bernie ',
    alleyPlacement: 0,
    earlyPickUp: 0,
    okToRoll: 0,
    negotiatedFill: 0,
    cow: 1,
    sos: 0,
    cabOver: 0,
    permittedCan: 0,
    permitNumber: null,
    textOnWay: '+17199898061',
    profileNumber: null,
    signatureRequired: 0,
    customerProvidedProfile: 0,
    priority: 0,
    step: null,
    canId: null,
    createdBy: 'smoore',
    createdDate: '2019-08-21T17:59:40.394Z',
    modifiedBy: 'smoore',
    modifiedDate: '2019-08-21T18:01:06.948Z',
    deleted: 0,
    index: 0,
  },
];

export const FINALS = [
  {
    location1: {
      id: 847251,
      name: '13862 West Tufts Avenue, Morrison, CO, 80465',
      description: null,
      type: 'LOCATION',
      waypointType: null,
      waypointName: null,
      location: 'Object',
      createdBy: 'smoore',
      createdDate: '2019-04-05T16:36:01.751Z',
      modifiedBy: null,
      modifiedDate: '2019-04-05T16:36:01.751Z',
    },
    location2: {
      id: null,
      name: null,
      description: null,
      type: null,
      waypointType: null,
      waypointName: null,
      location: 'Object',
      createdBy: null,
      createdDate: null,
      modifiedBy: null,
      modifiedDate: null,
    },
    driver: {
      truck: 'Object',
      id: null,
      name: null,
      username: null,
      photo: null,
      createdBy: null,
      createdDate: null,
      modifiedBy: null,
      modifiedDate: null,
      deleted: null,
    },
    id: 201473,
    documentId: null,
    templateId: 1,
    trackingDocId: null,
    status: 'UNASSIGNED',
    action: 'FINAL',
    size: '30',
    material: 'C & D',
    scheduledDate: '2019-09-07',
    scheduledStart: null,
    scheduledEnd: null,
    poNumber: null,
    contactName: 'Derek',
    contactNumber: '720-203-0704',
    customerName: 'Merica, Derek',
    instructions: null,
    alleyPlacement: 0,
    earlyPickUp: 0,
    okToRoll: 0,
    negotiatedFill: 0,
    cow: 1,
    sos: 0,
    cabOver: 0,
    permittedCan: 0,
    permitNumber: null,
    textOnWay: '+17202030704',
    profileNumber: null,
    signatureRequired: 0,
    customerProvidedProfile: 0,
    priority: 0,
    step: null,
    canId: null,
    createdBy: 'smoore',
    createdDate: '2019-08-21T16:22:56.718Z',
    modifiedBy: null,
    modifiedDate: '2019-08-21T16:22:56.718Z',
    deleted: 0,
    index: 0,
  },
  {
    location1: {
      id: 1065799,
      name: '1355 Krameria Street, Denver, CO, 80220',
      description: null,
      type: 'LOCATION',
      waypointType: null,
      waypointName: null,
      location: 'Object',
      createdBy: 'smoore',
      createdDate: '2019-08-22T15:52:43.801Z',
      modifiedBy: null,
      modifiedDate: '2019-08-22T15:52:43.801Z',
    },
    location2: {
      id: null,
      name: null,
      description: null,
      type: null,
      waypointType: null,
      waypointName: null,
      location: 'Object',
      createdBy: null,
      createdDate: null,
      modifiedBy: null,
      modifiedDate: null,
    },
    driver: {
      truck: 'Object',
      id: null,
      name: null,
      username: null,
      photo: null,
      createdBy: null,
      createdDate: null,
      modifiedBy: null,
      modifiedDate: null,
      deleted: null,
    },
    id: 201777,
    documentId: null,
    templateId: 1,
    trackingDocId: null,
    status: 'UNASSIGNED',
    action: 'FINAL',
    size: '30',
    material: 'C & D',
    scheduledDate: '2019-09-07',
    scheduledStart: null,
    scheduledEnd: null,
    poNumber: null,
    contactName: null,
    contactNumber: null,
    customerName: 'Triad Service Solutions',
    instructions: '720-939-8319  Diego',
    alleyPlacement: 0,
    earlyPickUp: 0,
    okToRoll: 0,
    negotiatedFill: 0,
    cow: 0,
    sos: 0,
    cabOver: 0,
    permittedCan: 0,
    permitNumber: null,
    textOnWay: '+17209398319',
    profileNumber: null,
    signatureRequired: 0,
    customerProvidedProfile: 0,
    priority: 0,
    step: null,
    canId: null,
    createdBy: 'smoore',
    createdDate: '2019-08-22T15:55:25.219Z',
    modifiedBy: null,
    modifiedDate: '2019-08-22T15:55:25.219Z',
    deleted: 0,
    index: 0,
  },
  {
    location1: {
      id: 1071796,
      name: '8768 Apache Plume Drive, Parker, CO, 80134',
      description: null,
      type: 'LOCATION',
      waypointType: null,
      waypointName: null,
      location: 'Object',
      createdBy: 'smoore',
      createdDate: '2019-08-26T23:26:43.332Z',
      modifiedBy: null,
      modifiedDate: '2019-08-26T23:26:43.332Z',
    },
    location2: {
      id: null,
      name: null,
      description: null,
      type: null,
      waypointType: null,
      waypointName: null,
      location: 'Object',
      createdBy: null,
      createdDate: null,
      modifiedBy: null,
      modifiedDate: null,
    },
    driver: {
      truck: 'Object',
      id: null,
      name: null,
      username: null,
      photo: null,
      createdBy: null,
      createdDate: null,
      modifiedBy: null,
      modifiedDate: null,
      deleted: null,
    },
    id: 202708,
    documentId: null,
    templateId: 1,
    trackingDocId: null,
    status: 'UNASSIGNED',
    action: 'FINAL',
    size: '40',
    material: 'C & D',
    scheduledDate: '2019-09-06',
    scheduledStart: null,
    scheduledEnd: null,
    poNumber: '19158600',
    contactName: 'Mario',
    contactNumber: '303.709.5716',
    customerName: 'Cleanup Contractors LLC',
    instructions: 'COW Mario   (303) 709-5716',
    alleyPlacement: 0,
    earlyPickUp: 0,
    okToRoll: 0,
    negotiatedFill: 0,
    cow: 1,
    sos: 0,
    cabOver: 0,
    permittedCan: 0,
    permitNumber: null,
    textOnWay: null,
    profileNumber: null,
    signatureRequired: 0,
    customerProvidedProfile: 0,
    priority: 0,
    step: null,
    canId: null,
    createdBy: 'smoore',
    createdDate: '2019-08-26T23:31:06.012Z',
    modifiedBy: null,
    modifiedDate: '2019-08-26T23:31:06.012Z',
    deleted: 0,
    index: 0,
  },
  {
    location1: {
      id: 1053575,
      name: '13124 Acres Green Drive, Lone Tree, CO, 80124',
      description: null,
      type: 'LOCATION',
      waypointType: null,
      waypointName: null,
      location: 'Object',
      createdBy: 'smoore',
      createdDate: '2019-08-14T23:01:37.742Z',
      modifiedBy: null,
      modifiedDate: '2019-08-14T23:01:37.742Z',
    },
    location2: {
      id: 3,
      name: '5970 US-85, Sedalia, CO 80135',
      description: null,
      type: 'WAYPOINT',
      waypointType: 'LANDFILL',
      waypointName: 'Sedalia Landfill',
      location: 'Object',
      createdBy: 'dispatch3',
      createdDate: '2016-10-12T14:16:51.204Z',
      modifiedBy: null,
      modifiedDate: '2017-01-18T18:59:33.744Z',
    },
    driver: {
      truck: 'Object',
      id: null,
      name: null,
      username: null,
      photo: null,
      createdBy: null,
      createdDate: null,
      modifiedBy: null,
      modifiedDate: null,
      deleted: null,
    },
    id: 201477,
    documentId: null,
    templateId: 1,
    trackingDocId: null,
    status: 'UNASSIGNED',
    action: 'FINAL',
    size: '30',
    material: 'C & D',
    scheduledDate: '2019-09-05',
    scheduledStart: null,
    scheduledEnd: null,
    poNumber: null,
    contactName: null,
    contactNumber: null,
    customerName: 'Denver Artisan Decks',
    instructions: null,
    alleyPlacement: 0,
    earlyPickUp: 0,
    okToRoll: 0,
    negotiatedFill: 1,
    cow: 0,
    sos: 0,
    cabOver: 0,
    permittedCan: 0,
    permitNumber: null,
    textOnWay: null,
    profileNumber: null,
    signatureRequired: 0,
    customerProvidedProfile: 0,
    priority: 0,
    step: null,
    canId: null,
    createdBy: 'alycia.hilzer@5280waste.com',
    createdDate: '2019-08-21T16:26:50.659Z',
    modifiedBy: null,
    modifiedDate: '2019-08-21T16:26:50.659Z',
    deleted: 0,
    index: 0,
  },
];
