export const up = async (migrationBuilder, schema) => {
  await migrationBuilder.raw(`CREATE FOREIGN TABLE ${schema}.f_subscriptions (
      id int4,
      status text,
      csr_email text,
      last_billed_at timestamp,
      next_billing_date date,
      custom_rates_group_id int4,
      business_line_id int4,
      business_unit_id int4,
      customer_id int4,
      job_site_id int4,
      service_area_id int4,
      customer_job_site_id int4,
      job_site_note text,
      job_site_contact_id int4,
      job_site_contact_text_only bool,
      driver_instructions text,
      permit_id int4,
      best_time_to_come_from text,
      best_time_to_come_to text,
      early_pick bool,
      to_roll bool ,
      high_priority bool,
      someone_on_site bool,
      third_party_hauler_id int4,
      subscription_contact_id int4,
      start_date date,
      end_date date,
      billing_cycle text,
      billing_type text,
      anniversary_billing bool,
      next_billing_period_from date,
      next_billing_period_to date,
      equipment_type text,
      unlock_overrides bool,
      payment_method text,
      promo_id int4,
      billable_services_total numeric,
      billable_line_items_total numeric,
      before_taxes_total numeric,
      initial_grand_total numeric,
      grand_total numeric,
      billable_subscription_orders_total numeric,
      current_subscription_price numeric,
      reason text,
      reason_description text,
      hold_subscription_until date,
      service_frequency text,
      alley_placement bool,
      signature_required bool,
      rates_changed bool,
      min_billing_periods int4,
      subscription_end_email_sent bool,
      subscription_resume_email_sent bool,
      override_credit_limit bool,
      invoiced_date date,
      recurring_grand_total numeric,
      paid_total numeric,
      period_from date,
      period_to date,
      purchase_order_id int4,
      csr_comment text,
      po_required bool,
      "permitRequired" bool,
      cab_over bool,
      on_hold_email_sent bool,
      on_hold_notify_sales_rep bool,
      on_hold_notify_main_contact bool,
      competitor_id int4,
      competitor_expiration_date date,
      created_at timestamp,
      updated_at timestamp)
    SERVER fdw_pricing OPTIONS(table_name 'subscriptions')`);
};

export const down = async (migrationBuilder, schema) => {
  await migrationBuilder.raw(`DROP FOREIGN TABLE ${schema}.f_subscriptions`);
};
