export const up = async (migrationBuilder, schema) => {
  await migrationBuilder.raw(`CREATE FOREIGN TABLE ${schema}.f_customers (
    id int4,
    customer_group_id int4,
    business_unit_id int4,
    email text,
    signature_required bool,
    po_required bool,
    business_name text,
    first_name text,
    last_name text,
    contact_id int4,
    "name" text,
    alternate_id text,
    owner_id int4,
    sales_id text,
    invoice_construction text,
    on_account bool,
    credit_limit numeric,
    billing_cycle text,
    payment_terms text,
    balance numeric,
    add_finance_charges bool,
    apr_type text,
    finance_charge numeric,
    mailing_address_line_1 text,
    mailing_address_line_2 text,
    mailing_city text,
    mailing_state text,
    mailing_zip text,
    full_mailing_address text,
    billing_address_line_1 text,
    billing_address_line_2 text,
    billing_city text,
    billing_state text,
    billing_zip text,
    full_billing_address text,
    send_invoices_by_post bool,
    send_invoices_by_email bool,
    attach_ticket_pref bool,
    attach_media_pref bool,
    invoice_emails _text,
    statement_emails _text,
    notification_emails _text,
    general_note text,
    popup_note text,
    status text,
    is_autopay_exist bool,
    autopay_type text,
    billing_note text,
    work_order_required bool,
    job_site_required bool,
    can_tare_weight_required bool,
    grading_required bool,
    grading_notification bool,
    self_service_order_allowed bool,
    walkup bool,
    sp_used bool,
    created_at timestamp,
    updated_at timestamp,
    reference_number text,
    hauler_srn text,
    work_order_note text,
    main_phone_number text,
    card_connect_id text,
    fluid_pay_id text,
    invoice_send_method text)
  SERVER fdw_core OPTIONS(table_name 'customers')`);
};

export const down = async (migrationBuilder, schema) => {
  await migrationBuilder.raw(`DROP FOREIGN TABLE ${schema}.f_customers`);
};
