export const FETCH_AVAILABLE_RESOURCE_LOGINS_REQUEST =
  '@lobby/FETCH_AVAILABLE_RESOURCE_LOGINS_REQUEST';
export const FETCH_AVAILABLE_RESOURCE_LOGINS_SUCCESS =
  '@lobby/FETCH_AVAILABLE_RESOURCE_LOGINS_SUCCESS';
export const FETCH_AVAILABLE_RESOURCE_LOGINS_FAILURE =
  '@lobby/FETCH_AVAILABLE_RESOURCE_LOGINS_FAILURE';
