import { GetOrderQuery } from '../../../graphql/api';

export const getLoadInitialValues = (order: GetOrderQuery['order']) => ({
  status: order.status,
  id: order.id,
  note: order.note,
  type: order.type,
  customer: order.customer,
  customerTruck: order.customerTruck,
  containerId: order.container?.id,
  PONumber: order.PONumber,
  WONumber: order.WONumber,
  weightIn: order.weightIn,
  weightInType: order.weightInType,
  weightInSource: order.weightInSource,
  weightInUnit: order.weightInUnit,
  weightInTimestamp: order.weightInTimestamp,
  weightOut: order.weightOut,
  weightOutSource: order.weightOutSource,
  weightOutUnit: order.weightOutUnit,
  weightOutType: order.weightOutType,
  weightOutTimestamp: order.weightOutTimestamp,
  priceGroupId: order.priceGroupId,
  billableServiceId: order.billableService?.id,
  billableServiceName: order.billableService?.description,
  bypassScale: order.bypassScale,
  useTare: order.useTare,
  truckTare: order.truckTare ?? order.customerTruck?.emptyWeight ?? 0,
  canTare: order.canTare ?? order.container?.emptyWeight ?? 0,
  taxTotal: order.taxTotal,
  taxDistricts: order.taxDistricts,
  initialOrderTotal: order.initialOrderTotal,
  minimalWeight: order.minimalWeight,
  weightScaleUom: order.weightScaleUom,
  licensePlate: order.nonCommercialTruck?.licensePlate,
});
