export const FETCH_SIZES_REQUEST = '@sizes/FETCH_SIZES_REQUEST';
export const FETCH_SIZES_SUCCESS = '@sizes/FETCH_SIZES_SUCCESS';
export const FETCH_SIZES_FAILURE = '@sizes/FETCH_SIZES_FAILURE';

export const FETCH_SIZE_REQUEST = '@sizes/FETCH_SIZE_REQUEST';
export const FETCH_SIZE_SUCCESS = '@sizes/FETCH_SIZE_SUCCESS';
export const FETCH_SIZE_FAILURE = '@sizes/FETCH_SIZE_FAILURE';

export const REMOVE_SIZE_REQUEST = '@sizes/REMOVE_SIZE_REQUEST';
export const REMOVE_SIZE_SUCCESS = '@sizes/REMOVE_SIZE_SUCCESS';
export const REMOVE_SIZE_FAILURE = '@sizes/REMOVE_SIZE_FAILURE';

export const UPDATE_SIZE_REQUEST = '@sizes/UPDATE_SIZE_REQUEST';
export const UPDATE_SIZE_SUCCESS = '@sizes/UPDATE_SIZE_SUCCESS';
export const UPDATE_SIZE_FAILURE = '@sizes/UPDATE_SIZE_FAILURE';

export const CREATE_SIZE_REQUEST = '@sizes/CREATE_SIZE_REQUEST';
export const CREATE_SIZE_SUCCESS = '@sizes/CREATE_SIZE_SUCCESS';
export const CREATE_SIZE_FAILURE = '@sizes/CREATE_SIZE_FAILURE';
