export const FETCH_DRIVERS_REQUEST = '@drivers/FETCH_DRIVERS_REQUEST';
export const FETCH_DRIVERS_SUCCESS = '@drivers/FETCH_DRIVERS_SUCCESS';
export const FETCH_DRIVERS_FAILURE = '@drivers/FETCH_DRIVERS_FAILURE';
export const RECEIVE_DRIVERS = '@drivers/RECEIVE_DRIVERS';
export const EXPORT_DRIVERS_REQUEST = '@drivers/EXPORT_DRIVERS_REQUEST';
export const EXPORT_DRIVERS_SUCCESS = '@drivers/EXPORT_DRIVERS_SUCCESS';
export const EXPORT_DRIVERS_FAILURE = '@drivers/EXPORT_DRIVERS_FAILURE';

export const UPDATE_DRIVER_LOC_REQUEST = '@drivers/UPDATE_DRIVER_LOC_REQUEST';
export const UPDATE_DRIVER_LOC_SUCCESS = '@drivers/UPDATE_DRIVER_LOC_SUCCESS';
export const UPDATE_DRIVER_LOC_FAILURE = '@drivers/UPDATE_DRIVER_LOC_FAILURE';

export const ADD_DRIVER = '@drivers/ADD_DRIVER';
export const REMOVE_DRIVER = '@drivers/REMOVE_DRIVER';
export const ADD_ALL_DRIVERS = '@drivers/ADD_ALL_DRIVERS';
export const SET_FILTERED_DRIVERS = '@drivers/SET_FILTERED_DRIVERS';
