export const FETCH_USERS_REQUEST = '@users/FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = '@users/FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = '@users/FETCH_USERS_FAILURE';

export const CREATE_USER_REQUEST = '@users/CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = '@users/CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = '@users/CREATE_USER_FAILURE';

export const UPDATE_USER_REQUEST = '@users/UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = '@users/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = '@users/UPDATE_USER_FAILURE';

export const UPDATE_PASSWORD_REQUEST = '@users/UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = '@users/UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = '@users/UPDATE_PASSWORD_FAILURE';

export const CHANGE_ROLE_REQUEST = '@users/CHANGE_ROLE_REQUEST';
export const CHANGE_ROLE_SUCCESS = '@users/CHANGE_ROLE_SUCCESS';
export const CHANGE_ROLE_FAILURE = '@users/CHANGE_ROLE_FAILURE';

export const SELECT_USER = '@users/SELECT_USER';
export const DESELECT_USER = '@users/DESELECT_USER';
