export const RECEIVE_LOCATION = '@locations/RECEIVE_LOCATION';
export const FORGET_LOCATION = '@locations/FORGET_LOCATION';

export const CREATE_LOCATION_REQUEST = '@locations/CREATE_LOCATION_REQUEST';
export const CREATE_LOCATION_SUCCESS = '@locations/CREATE_LOCATION_SUCCESS';
export const CREATE_LOCATION_FAILURE = '@locations/CREATE_LOCATION_FAILURE';

export const FETCH_TRUCKS_REQUEST = '@locations/FETCH_TRUCKS_REQUEST';
export const FETCH_TRUCKS_SUCCESS = '@locations/FETCH_TRUCKS_SUCCESS';
export const FETCH_TRUCKS_FAILURE = '@locations/FETCH_TRUCKS_FAILURE';

export const FETCH_TRUCK_REQUEST = '@locations/FETCH_TRUCK_REQUEST';
export const FETCH_TRUCK_SUCCESS = '@locations/FETCH_TRUCK_SUCCESS';
export const FETCH_TRUCK_FAILURE = '@locations/FETCH_TRUCK_FAILURE';

export const CREATE_TRUCK_REQUEST = '@locations/CREATE_TRUCK_REQUEST';
export const CREATE_TRUCK_SUCCESS = '@locations/CREATE_TRUCK_SUCCESS';
export const CREATE_TRUCK_FAILURE = '@locations/CREATE_TRUCK_FAILURE';

export const UPDATE_TRUCK_REQUEST = '@locations/UPDATE_TRUCK_REQUEST';
export const UPDATE_TRUCK_SUCCESS = '@locations/UPDATE_TRUCK_SUCCESS';
export const UPDATE_TRUCK_FAILURE = '@locations/UPDATE_TRUCK_FAILURE';

export const REMOVE_TRUCK_REQUEST = '@locations/REMOVE_TRUCK_REQUEST';
export const REMOVE_TRUCK_SUCCESS = '@locations/REMOVE_TRUCK_SUCCESS';
export const REMOVE_TRUCK_FAILURE = '@locations/REMOVE_TRUCK_FAILURE';

export const FETCH_WAYPOINT_REQUEST = '@locations/FETCH_WAYPOINT_REQUEST';
export const FETCH_WAYPOINT_SUCCESS = '@locations/FETCH_WAYPOINT_SUCCESS';
export const FETCH_WAYPOINT_FAILURE = '@locations/FETCH_WAYPOINT_FAILURE';

export const FETCH_WAYPOINTS_REQUEST = '@locations/FETCH_WAYPOINTS_REQUEST';
export const FETCH_WAYPOINTS_SUCCESS = '@locations/FETCH_WAYPOINTS_SUCCESS';
export const FETCH_WAYPOINTS_FAILURE = '@locations/FETCH_WAYPOINTS_FAILURE';

export const CREATE_WAYPOINT_REQUEST = '@locations/CREATE_WAYPOINT_REQUEST';
export const CREATE_WAYPOINT_SUCCESS = '@locations/CREATE_WAYPOINT_SUCCESS';
export const CREATE_WAYPOINT_FAILURE = '@locations/CREATE_WAYPOINT_FAILURE';

export const UPDATE_WAYPOINT_REQUEST = '@locations/UPDATE_WAYPOINT_REQUEST';
export const UPDATE_WAYPOINT_SUCCESS = '@locations/UPDATE_WAYPOINT_SUCCESS';
export const UPDATE_WAYPOINT_FAILURE = '@locations/UPDATE_WAYPOINT_FAILURE';

export const REMOVE_WAYPOINT_REQUEST = '@locations/REMOVE_WAYPOINT_REQUEST';
export const REMOVE_WAYPOINT_SUCCESS = '@locations/REMOVE_WAYPOINT_SUCCESS';
export const REMOVE_WAYPOINT_FAILURE = '@locations/REMOVE_WAYPOINT_FAILURE';
