const constants = {
  driverApp: {
    androidName: 'com.starlightsoftwaresolutions.drivers',
    androidVersion: '1.0.0',
    iosVersion: '1.0.0',
    iosName: 'com.starlightsoftwaresolutions.drivers',
  },
  can: {
    action: {
      MOVE: 'MOVE',
      PICKUP: 'PICKUP',
      DROPOFF: 'DROPOFF',
      TRANSFER: 'TRANSFER',
      NOTE: 'NOTE',
      UPDATE: 'UPDATE',
      REMOVE: 'REMOVE',
      CREATE: 'CREATE',
    },
    size: ['10', '12', '20', '30', '40', '40CT'],
  },
  trip: {
    tripType: {
      PRE_TRIP: 'PRE_TRIP',
      POST_TRIP: 'POST_TRIP',
    },
  },
  location: {
    type: {
      LOCATION: 'LOCATION',
      WAYPOINT: 'WAYPOINT',
    },
    waypointType: {
      HOME_YARD: 'HOME_YARD',
      LANDFILL_STORAGE_YARD: 'LANDFILL_STORAGE_YARD',
      LANDFILL: 'LANDFILL',
      RECYCLE_CENTER: 'RECYCLE_CENTER',
      STORAGE_YARD: 'STORAGE_YARD',
      TRANSFER_CENTER: 'TRANSFER_CENTER',
    },
  },
  workOrder: {
    action: {
      SPOT: 'SPOT',
      FINAL: 'FINAL',
      FINAL_SUSPEND: 'FINAL SUSPEND',
      FINAL_RESUME: 'FINAL RESUME',
      SWITCH: 'SWITCH',
      SWITCH_SUSPEND: 'SWITCH SUSPEND',
      SWITCH_RESUME: 'SWITCH RESUME',
      DUMP_AND_RETURN: 'DUMP & RETURN',
      DUMP_AND_RETURN_SUSPEND: 'DUMP & RETURN SUSPEND',
      DUMP_AND_RETURN_RESUME: 'DUMP & RETURN RESUME',
      LIVE_LOAD: 'LIVE LOAD',
      LIVE_LOAD_SUSPEND: 'LIVE LOAD SUSPEND',
      LIVE_LOAD_RESUME: 'LIVE LOAD RESUME',
      PICKUP: 'PICKUP CAN',
      DROPOFF: 'DROPOFF CAN',
      RELOCATE: 'RELOCATE',
      REPOSITION: 'REPOSITION',
      GENERAL_PURPOSE: 'GENERAL PURPOSE',
    },
    haulingAction: {
      SPOT: 'delivery',
      SWITCH: 'switch',
      FINAL: 'final',
      RELOCATE: 'relocate',
      REPOSITION: 'reposition',
      DUMP_AND_RETURN: 'dump&Return',
      LIVE_LOAD: 'liveLoad',
      GENERAL_PURPOSE: 'generalPurpose',
    },
    status: {
      UNASSIGNED: 'UNASSIGNED',
      ASSIGNED: 'ASSIGNED',
      INPROGRESS: 'INPROGRESS',
      COMPLETED: 'COMPLETED',
      CANCELED: 'CANCELED',
    },
    material: [
      'Asphalt',
      'C & D',
      'Cardboard Recycle',
      'Concrete Recycle',
      'Drywall Recycle',
      'Heavy C & D',
      'Manifested Friable',
      'Manifested Non-Friable',
      'Metal Recycle',
      'Wood Recycle',
    ],
    note: {
      type: {
        MANIFEST: 'MANIFEST',
        NOTE: 'NOTE',
        SCALETICKET: 'SCALETICKET',
        WEIGHT_RECORD: 'WEIGHT_RECORD',
        SIGNED_DOC: 'SIGNED_DOC',
        TRANSITION: 'TRANSITION',
      },
      unittype: {
        YARDS: 'YARDS',
        TONS: 'TONS',
      },
      transitionState: {
        START_WORK_ORDER: 'START WORK ORDER',
        ARRIVE_ON_SITE: 'ARRIVE ON SITE',
        ARRIVE_ON_SITE2: 'ARRIVE ON SITE2',
        SIGNATURE: 'SIGNATURE',
        START_SERVICE: 'START SERVICE',
        START_SERVICE2: 'START SERVICE2',
        DROP_CAN: 'DROP CAN',
        PICKUP_CAN: 'PICKUP CAN',
        SECOND_LOCATION: 'SECOND LOCATION',
        FINISH_SERVICE: 'FINISH SERVICE',
        FINISH_SERVICE2: 'FINISH SERVICE2',
        // RECORD_MANIFESTS: 'RECORD MANIFESTS',
        GOING_TO_FILL: 'GOING TO FILL',
        ARRIVE_AT_FILL: 'ARRIVE AT FILL',
        FINISH_DISPOSAL: 'FINISH DISPOSAL',
        RECORD_WEIGHT_TICKETS: 'RECORD WEIGHT TICKETS',
        RETURNING_TO_JOBSITE: 'RETURNING TO JOBSITE',
        REASSIGNMENT: 'REASSIGNMENT',
        WORK_ORDER_COMPLETE: 'WORK ORDER COMPLETE',
        SPECIAL_INSTRUCTIONS: 'SPECIAL INSTRUCTIONS',
        //
        RESUME_WORK_ORDER: 'RESUME WORK ORDER',
        GOING_TO_SUSPENSION_SITE: 'GOING TO SUSPENSION SITE',
        PICKUP_STAGED_CAN: 'PICKUP STAGED CAN',
        ARRIVE_AT_SUSPENSION_SITE: 'ARRIVE AT SUSPENSION SITE',
        DROP_STAGED_CAN: 'DROP STAGED CAN',
        SUSPEND_WORK_ORDER: 'SUSPEND WORK ORDER',
      },
    },
  },
  import: {
    type: {
      APPEND: 'APPEND',
      UPDATE: 'UPDATE',
      DELETE: 'DELETE',
    },
  },
  timezone: {
    'America/Denver': 'America/Denver',
    'America/Detroit': 'America/Detroit',
    'America/Chicago': 'America/Chicago',
    'America/Phoenix': 'America/Phoenix',
    'America/Los_Angeles': 'America/Los_Angeles',
    'America/New_York': 'America/New_York',
  },
};
const {
  workOrder: {
    action,
    note: { transitionState: state },
  },
} = constants;
const commonSteps = [
  state.START_WORK_ORDER,
  state.ARRIVE_ON_SITE,
  state.START_SERVICE,
  state.FINISH_SERVICE,
  state.WORK_ORDER_COMPLETE,
];
const finalSteps = [
  ...commonSteps,
  state.SIGNATURE,
  state.PICKUP_CAN,
  // state.RECORD_MANIFESTS,
  state.GOING_TO_FILL,
  state.ARRIVE_AT_FILL,
  state.FINISH_DISPOSAL,
  state.RECORD_WEIGHT_TICKETS,
];
export const actionTransitionsRelation = {
  [action.SPOT]: [...commonSteps, state.SIGNATURE, state.DROP_CAN],
  [action.PICKUP]: [
    state.START_WORK_ORDER,
    state.ARRIVE_ON_SITE,
    state.PICKUP_CAN,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.DROPOFF]: [
    state.START_WORK_ORDER,
    state.ARRIVE_ON_SITE,
    state.DROP_CAN,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.GENERAL_PURPOSE]: [
    state.START_WORK_ORDER,
    state.ARRIVE_ON_SITE,
    state.SPECIAL_INSTRUCTIONS,
    state.SIGNATURE,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.FINAL]: finalSteps,
  [action.DUMP_AND_RETURN]: [
    ...finalSteps,
    state.RETURNING_TO_JOBSITE,
    state.ARRIVE_ON_SITE2,
    state.START_SERVICE2,
    state.DROP_CAN,
    state.FINISH_SERVICE2,
  ],
  [action.LIVE_LOAD]: [...finalSteps, state.DROP_CAN],
  [action.RELOCATE]: [...commonSteps, state.PICKUP_CAN, state.SECOND_LOCATION, state.DROP_CAN],
  [action.REPOSITION]: [...commonSteps, state.PICKUP_CAN, state.DROP_CAN],
  [action.SWITCH]: [...finalSteps, state.DROP_CAN],
};
const actionTransitionsOrdered = {
  [action.SPOT]: [
    state.START_WORK_ORDER,
    state.ARRIVE_ON_SITE,
    state.START_SERVICE,
    state.SIGNATURE,
    state.DROP_CAN,
    state.FINISH_SERVICE,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.FINAL]: [
    state.START_WORK_ORDER,
    state.ARRIVE_ON_SITE,
    state.START_SERVICE,
    state.SIGNATURE,
    state.PICKUP_CAN,
    state.FINISH_SERVICE,
    state.GOING_TO_FILL,
    state.ARRIVE_AT_FILL,
    state.FINISH_DISPOSAL,
    state.RECORD_WEIGHT_TICKETS,
    // state.RECORD_MANIFESTS,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.FINAL_SUSPEND]: [
    state.GOING_TO_SUSPENSION_SITE,
    state.ARRIVE_AT_SUSPENSION_SITE,
    state.DROP_CAN,
    state.SUSPEND_WORK_ORDER,
  ],
  [action.FINAL_RESUME]: [
    state.RESUME_WORK_ORDER,
    state.GOING_TO_SUSPENSION_SITE,
    state.ARRIVE_AT_SUSPENSION_SITE,
    state.PICKUP_CAN,
    state.GOING_TO_FILL,
    state.ARRIVE_AT_FILL,
    state.FINISH_DISPOSAL,
    state.RECORD_WEIGHT_TICKETS,
    // state.RECORD_MANIFESTS,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.SWITCH]: [
    state.START_WORK_ORDER,
    state.ARRIVE_ON_SITE,
    state.START_SERVICE,
    state.SIGNATURE,
    state.DROP_CAN,
    state.PICKUP_CAN,
    state.FINISH_SERVICE,
    state.GOING_TO_FILL,
    state.ARRIVE_AT_FILL,
    state.FINISH_DISPOSAL,
    state.RECORD_WEIGHT_TICKETS,
    // state.RECORD_MANIFESTS,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.SWITCH_SUSPEND]: [
    state.GOING_TO_SUSPENSION_SITE,
    state.ARRIVE_AT_SUSPENSION_SITE,
    state.DROP_CAN,
    state.SUSPEND_WORK_ORDER,
  ],
  [action.SWITCH_RESUME]: [
    state.RESUME_WORK_ORDER,
    state.GOING_TO_SUSPENSION_SITE,
    state.ARRIVE_AT_SUSPENSION_SITE,
    state.PICKUP_CAN,
    state.GOING_TO_FILL,
    state.ARRIVE_AT_FILL,
    state.FINISH_DISPOSAL,
    state.RECORD_WEIGHT_TICKETS,
    // state.RECORD_MANIFESTS,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.LIVE_LOAD]: [
    state.START_WORK_ORDER,
    state.ARRIVE_ON_SITE,
    state.START_SERVICE,
    state.SIGNATURE,
    state.DROP_CAN,
    state.PICKUP_CAN,
    state.FINISH_SERVICE,
    state.GOING_TO_FILL,
    state.ARRIVE_AT_FILL,
    state.FINISH_DISPOSAL,
    state.RECORD_WEIGHT_TICKETS,
    // state.RECORD_MANIFESTS,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.LIVE_LOAD_SUSPEND]: [
    state.GOING_TO_SUSPENSION_SITE,
    state.ARRIVE_AT_SUSPENSION_SITE,
    state.DROP_CAN,
    state.SUSPEND_WORK_ORDER,
  ],
  [action.LIVE_LOAD_RESUME]: [
    state.RESUME_WORK_ORDER,
    state.GOING_TO_SUSPENSION_SITE,
    state.ARRIVE_AT_SUSPENSION_SITE,
    state.PICKUP_CAN,
    state.GOING_TO_FILL,
    state.ARRIVE_AT_FILL,
    state.FINISH_DISPOSAL,
    state.RECORD_WEIGHT_TICKETS,
    // state.RECORD_MANIFESTS,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.DUMP_AND_RETURN]: [
    state.START_WORK_ORDER,
    state.ARRIVE_ON_SITE,
    state.START_SERVICE,
    state.SIGNATURE,
    state.PICKUP_CAN,
    state.FINISH_SERVICE,
    state.GOING_TO_FILL,
    state.ARRIVE_AT_FILL,
    state.FINISH_DISPOSAL,
    state.RECORD_WEIGHT_TICKETS,
    // state.RECORD_MANIFESTS,
    state.RETURNING_TO_JOBSITE,
    state.ARRIVE_ON_SITE2,
    state.START_SERVICE2,
    state.DROP_CAN,
    state.FINISH_SERVICE2,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.DUMP_AND_RETURN_SUSPEND]: [
    state.GOING_TO_SUSPENSION_SITE,
    state.ARRIVE_AT_SUSPENSION_SITE,
    state.DROP_CAN,
    state.SUSPEND_WORK_ORDER,
  ],
  [action.DUMP_AND_RETURN_RESUME]: [
    state.RESUME_WORK_ORDER,
    state.GOING_TO_SUSPENSION_SITE,
    state.ARRIVE_AT_SUSPENSION_SITE,
    state.PICKUP_CAN,
    state.GOING_TO_FILL,
    state.ARRIVE_AT_FILL,
    state.FINISH_DISPOSAL,
    state.RECORD_WEIGHT_TICKETS,
    // state.RECORD_MANIFESTS,
    state.RETURNING_TO_JOBSITE,
    state.ARRIVE_ON_SITE2,
    state.START_SERVICE2,
    state.DROP_CAN,
    state.FINISH_SERVICE2,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.RELOCATE]: [
    state.START_WORK_ORDER,
    state.ARRIVE_ON_SITE,
    state.START_SERVICE,
    state.SIGNATURE,
    state.PICKUP_CAN,
    state.SECOND_LOCATION,
    state.DROP_CAN,
    state.FINISH_SERVICE,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.REPOSITION]: [
    state.START_WORK_ORDER,
    state.ARRIVE_ON_SITE,
    state.START_SERVICE,
    state.SIGNATURE,
    state.PICKUP_CAN,
    state.DROP_CAN,
    state.FINISH_SERVICE,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.DROPOFF]: [
    state.START_WORK_ORDER,
    state.ARRIVE_ON_SITE,
    state.DROP_CAN,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.GENERAL_PURPOSE]: [
    state.START_WORK_ORDER,
    state.ARRIVE_ON_SITE,
    state.SPECIAL_INSTRUCTIONS,
    state.SIGNATURE,
    state.WORK_ORDER_COMPLETE,
  ],
  [action.PICKUP]: [
    state.START_WORK_ORDER,
    state.ARRIVE_ON_SITE,
    state.PICKUP_CAN,
    state.WORK_ORDER_COMPLETE,
  ],
};
constants.actionTransitionsRelation = actionTransitionsRelation;
constants.actionTransitionsOrdered = actionTransitionsOrdered;
export default constants;
