/trashapi/v1/auth/{tenantName}/configuration/login:
  get:
    $fs-ref: ./configuration-auth/get-login.yaml
  post:
    $fs-ref: ./configuration-auth/post-login.yaml

/trashapi/v1/auth/{tenantName}/configuration/logincb:
  get:
    $fs-ref: ./configuration-auth/logincb.yaml

/trashapi/v1/auth/{tenantName}/configuration/refresh:
  post:
    $fs-ref: ./configuration-auth/refresh.yaml

/trashapi/v1/auth/{tenantName}/configuration/logout:
  get:
    $fs-ref: ./configuration-auth/logout.yaml
