export const CREATE_CUSTOMER_REQUEST = '@manifest/CREATE_CUSTOMER_REQUEST';
export const CREATE_CUSTOMER_SUCCESS = '@manifest/CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_FAILURE = '@manifest/CREATE_CUSTOMER_FAILURE';

export const FETCH_CUSTOMERS_REQUEST = '@manifest/FETCH_CUSTOMERS_REQUEST';
export const FETCH_CUSTOMERS_SUCCESS = '@manifest/FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAILURE = '@manifest/FETCH_CUSTOMERS_FAILURE';

export const FETCH_ORG_CONFIG_REQUEST = '@manifest/FETCH_ORG_CONFIG_REQUEST';
export const FETCH_ORG_CONFIG_SUCCESS = '@manifest/FETCH_ORG_CONFIG_SUCCESS';
export const FETCH_ORG_CONFIG_FAILURE = '@manifest/FETCH_ORG_CONFIG_FAILURE';

export const CREATE_FACILITY_REQUEST = '@manifest/CREATE_FACILITY_REQUEST';
export const CREATE_FACILITY_SUCCESS = '@manifest/CREATE_FACILITY_SUCCESS';
export const CREATE_FACILITY_FAILURE = '@manifest/CREATE_FACILITY_FAILURE';

export const FETCH_FACILITIES_REQUEST = '@manifest/FETCH_FACILITIES_REQUEST';
export const FETCH_FACILITIES_SUCCESS = '@manifest/FETCH_FACILITIES_SUCCESS';
export const FETCH_FACILITIES_FAILURE = '@manifest/FETCH_FACILITIES_FAILURE';

export const FETCH_S_MANIFESTS_REQUEST = '@manifest/FETCH_S_MANIFESTS_REQUEST';
export const FETCH_S_MANIFESTS_SUCCESS = '@manifest/FETCH_S_MANIFESTS_SUCCESS';
export const FETCH_S_MANIFESTS_FAILURE = '@manifest/FETCH_S_MANIFESTS_FAILURE';
