export const FETCH_WO_NOTES_REQUEST = '@wonotes/FETCH_WO_NOTES_REQUEST';
export const FETCH_WO_NOTES_SUCCESS = '@wonotes/FETCH_WO_NOTES_SUCCESS';
export const FETCH_WO_NOTES_FAILURE = '@wonotes/FETCH_WO_NOTES_FAILURE';
export const RECEIVE_WO_NOTES = '@wonotes/RECEIVE_WO_NOTES';

export const CREATE_WO_NOTE_REQUEST = '@wonotes/CREATE_WO_NOTE_REQUEST';
export const CREATE_WO_NOTE_SUCCESS = '@wonotes/CREATE_WO_NOTE_SUCCESS';
export const CREATE_WO_NOTE_FAILURE = '@wonotes/CREATE_WO_NOTE_FAILURE';
export const FORGET_WO_NOTES = '@wonotes/FORGET_WO_NOTES';

export const FETCH_ALL_WO_NOTES_REQUEST = '@wonotes/FETCH_ALL_WO_NOTES_REQUEST';
export const FETCH_ALL_WO_NOTES_SUCCESS = '@wonotes/FETCH_ALL_WO_NOTES_SUCCESS';
export const FETCH_ALL_WO_NOTES_FAILURE = '@wonotes/FETCH_ALL_WO_NOTES_FAILURE';
