export const FETCH_SETTING_REQUEST = '@settings/FETCH_SETTING_REQUEST';
export const FETCH_SETTING_FAILURE = '@settings/FETCH_SETTING_FAILURE';
export const FETCH_SETTING_SUCCESS = '@settings/FETCH_SETTING_SUCCESS';
export const RECEIVE_MAP_SETTING = '@settings/RECEIVE_MAP_SETTING';
export const RECEIVE_DRIVER_SETTING = '@settings/RECEIVE_DRIVER_SETTING';
export const RECEIVE_SETTING = '@settings/RECEIVE_SETTING';

export const UPDATE_SETTING_REQUEST = '@settings/UPDATE_SETTING_REQUEST';
export const UPDATE_SETTING_SUCCESS = '@settings/UPDATE_SETTING_SUCCESS';
export const UPDATE_SETTING_FAILURE = '@settings/UPDATE_SETTING_FAILURE';
