FROM arm64v8/node:16-alpine

RUN mkdir /app

WORKDIR /app

COPY ./package.json /app/package.json
COPY ./yarn.lock /app/yarn.lock
ARG NPM_TOKEN
ENV NPM_TOKEN=$NPM_TOKEN

RUN test -n "$NPM_TOKEN" && echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > .npmrc
RUN echo "@starlightpro:registry=https://npm.pkg.github.com" >> .npmrc

RUN yarn install --ignore-engines
COPY . /app/
RUN yarn build

ENV NODE_ENV production

EXPOSE 3000
EXPOSE 3010

CMD yarn start
