export const FETCH_WO_SERVICES_REQUEST = '@services/CREATE_WO_REQUEST';
export const FETCH_WO_SERVICES_SUCCESS = '@services/FETCH_WO_SERVICES_SUCCESS';
export const FETCH_WO_SERVICES_FAILURE = '@services/FETCH_WO_SERVICES_FAILURE';

export const FETCH_WO_SERVICES_MATERIALS_REQUEST = '@services/FETCH_WO_SERVICES_MATERIALS_REQUEST';
export const FETCH_WO_SERVICES_MATERIALS_SUCCESS = '@services/FETCH_WO_SERVICES_MATERIALS_SUCCESS';
export const FETCH_WO_SERVICES_MATERIALS_FAILURE = '@services/FETCH_WO_SERVICES_MATERIALS_FAILURE';

export const FETCH_WO_SERVICES_DISPOSAL_SITES_REQUEST =
  '@services/FETCH_WO_SERVICES_DISPOSAL_SITES_REQUEST';
export const FETCH_WO_SERVICES_DISPOSAL_SITES_SUCCESS =
  '@services/FETCH_WO_SERVICES_DISPOSAL_SITES_SUCCESS';
export const FETCH_WO_SERVICES_DISPOSAL_SITES_FAILURE =
  '@services/FETCH_WO_SERVICES_DISPOSAL_SITES_FAILURE';
