export const FETCH_TEMPLATES_REQUEST = '@templates/FETCH_TEMPLATES_REQUEST';
export const FETCH_TEMPLATES_SUCCESS = '@templates/FETCH_TEMPLATES_SUCCESS';
export const FETCH_TEMPLATES_FAILURE = '@templates/FETCH_TEMPLATES_FAILURE';
export const GET_TEMPLATE_REQUEST = '@templates/GET_TEMPLATE_REQUEST';
export const GET_TEMPLATE_SUCCESS = '@templates/GET_TEMPLATE_SUCCESS';
export const GET_TEMPLATE_FAILURE = '@templates/GET_TEMPLATE_FAILURE';
export const CREATE_TEMPLATE_REQUEST = '@templates/CREATE_TEMPLATE_REQUEST';
export const CREATE_TEMPLATE_SUCCESS = '@templates/CREATE_TEMPLATE_SUCCESS';
export const CREATE_TEMPLATE_FAILURE = '@templates/CREATE_TEMPLATE_FAILURE';

export const FETCH_BILLABLE_SERVICES_REQUEST = '@templates/FETCH_BILLABLE_SERVICES_REQUEST';
export const FETCH_BILLABLE_SERVICES_SUCCESS = '@templates/FETCH_BILLABLE_SERVICES_SUCCESS';
export const FETCH_BILLABLE_SERVICES_FAILURE = '@templates/FETCH_BILLABLE_SERVICES_FAILURE';

export const UPDATE_TEMPLATE_REQUEST = '@templates/UPDATE_TEMPLATE_REQUEST';
export const UPDATE_TEMPLATE_SUCCESS = '@templates/UPDATE_TEMPLATE_SUCCESS';
export const UPDATE_TEMPLATE_FAILURE = '@templates/UPDATE_TEMPLATE_FAILURE';

export const DELETE_TEMPLATE_REQUEST = '@templates/DELETE_TEMPLATE_REQUEST';
export const DELETE_TEMPLATE_SUCCESS = '@templates/DELETE_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_FAILURE = '@templates/DELETE_TEMPLATE_FAILURE';

export const UPLOAD_LOGO_REQUEST = '@templates/UPLOAD_LOGO_REQUEST';
export const UPLOAD_LOGO_SUCCESS = '@templates/UPLOAD_LOGO_SUCCESS';
export const UPLOAD_LOGO_FAILURE = '@templates/UPLOAD_LOGO_FAILURE';
export const SET_TEMPLATE = '@templates/SET_TEMPLATE';
export const CLEAR_TEMPLATE = '@templates/CLEAR_TEMPLATE';
export const CLEAR_PREVIEW_IMAGE = '@templates/CLEAR_PREVIEW_IMAGE';
