export const FETCH_MATERIALS_REQUEST = '@materials/FETCH_MATERIALS_REQUEST';
export const FETCH_MATERIALS_SUCCESS = '@materials/FETCH_MATERIALS_SUCCESS';
export const FETCH_MATERIALS_FAILURE = '@materials/FETCH_MATERIALS_FAILURE';

export const FETCH_MATERIAL_REQUEST = '@materials/FETCH_MATERIAL_REQUEST';
export const FETCH_MATERIAL_SUCCESS = '@materials/FETCH_MATERIAL_SUCCESS';
export const FETCH_MATERIAL_FAILURE = '@materials/FETCH_MATERIAL_FAILURE';

export const REMOVE_MATERIAL_REQUEST = '@materials/REMOVE_MATERIAL_REQUEST';
export const REMOVE_MATERIAL_SUCCESS = '@materials/REMOVE_MATERIAL_SUCCESS';
export const REMOVE_MATERIAL_FAILURE = '@materials/REMOVE_MATERIAL_FAILURE';

export const UPDATE_MATERIAL_REQUEST = '@materials/UPDATE_MATERIAL_REQUEST';
export const UPDATE_MATERIAL_SUCCESS = '@materials/UPDATE_MATERIAL_SUCCESS';
export const UPDATE_MATERIAL_FAILURE = '@materials/UPDATE_MATERIAL_FAILURE';

export const CREATE_MATERIAL_REQUEST = '@materials/CREATE_MATERIAL_REQUEST';
export const CREATE_MATERIAL_SUCCESS = '@materials/CREATE_MATERIAL_SUCCESS';
export const CREATE_MATERIAL_FAILURE = '@materials/CREATE_MATERIAL_FAILURE';
