module.exports = {
  collectCoverageFrom: ['src/**/*.{js,jsx,mjs}'],
  setupFiles: [

  ],
  testMatch: ['<rootDir>/src/**/*.test.{js,jsx,mjs}'],
  testEnvironment: 'jsdom',
  testURL: 'http://localhost',
  transform: {
    // '^.+\\.(js|jsx|mjs)$': '<rootDir>/internal/jest/jestTransform.js',
    // '^.+\\.(css|pcss|scss)$': '<rootDir>/internal/jest/cssTransform.js',
    // '^(?!.*\\.(js|jsx|mjs|json)$)': '<rootDir>/internal/jest/fileTransform.js',
  },
  transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$'],
  moduleNameMapper: {
    '^react-native$': 'react-native-web',
    "^@root(.*)$": "<rootDir>/src$1",
    "^components(.*)$": "<rootDir>/src/components$1",
    "^utils(.*)$": "<rootDir>/src/utils$1",
    "^static(.*)$": "<rootDir>/src/static$1",
    "^state(.*)$": "<rootDir>/src/state$1",
    "^scenes(.*)$": "<rootDir>/src/scenes$1",
    "^helpers(.*)$": "<rootDir>/src/helpers$1",
    "^forms(.*)$": "<rootDir>/src/forms$1",
    "^src(.*)$": "<rootDir>/src/src$1"
  },
  globals: {
    google: {
      maps: {
        Animation: {},
        Circle: function () { },
        ControlPosition: {},
        DirectionsStatus: {},
        DirectionsTravelMode: {},
        DirectionsUnitSystem: {},
        DistanceMatrixElementStatus: {},
        DistanceMatrixStatus: {},
        ElevationStatus: {},
        GeocoderLocationType: {},
        GeocoderStatus: {},
        InfoWindow: function () { },
        KmlLayerStatus: {},
        LatLng: function () { },
        LatLngBounds: function () { },
        Map: function () {
          return {
            setTilt: function () { },
            mapTypes: {
              set: function () { },
            },
            overlayMapTypes: {
              insertAt: function () { },
              removeAt: function () { },
            },
            addListener: function () { },
            removeListener: function () { },
            setZoom: function () { },
            getZoom: function () { },
            setCenter: function () { },
          };
        },
        MapTypeControlStyle: {},
        MapTypeId: {
          HYBRID: '',
          ROADMAP: '',
          SATELLITE: '',
          TERRAIN: '',
        },
        Marker: function () { },
        MaxZoomStatus: {},
        NavigationControlStyle: {},
        Point: function () { },
        Polygon: function () { },
        Polyline: function () { },
        Rectangle: function () { },
        ScaleControlStyle: {},
        Size: function () { },
        StreetViewStatus: {},
        StrokePosition: {},
        SymbolPath: {},
        TransitMode: {},
        TransitRoutePreference: {},
        TravelMode: {},
        UnitSystem: {},
        ZoomControlStyle: {},
        event: {
          addListener: function () { },
          addListenerOnce: function () { },
          removeListener: function () { },
          trigger: function () { },
        },
      },
    },
  },
};
