export const FETCH_CANS_AT_WP_REQUEST = '@invboard/FETCH_CANS_AT_WP_REQUEST';
export const FETCH_CANS_AT_WP_SUCCESS = '@invboard/FETCH_CANS_AT_WP_SUCCESS';
export const FETCH_CANS_AT_WP_FAILURE = '@invboard/FETCH_CANS_AT_WP_FAILURE';
export const RECEIVE_INVENTORYBOARD = '@invboard/RECEIVE_INVENTORYBOARD';

export const FETCH_CANS_ON_TRUCKS_REQUEST = '@invboard/FETCH_CANS_ON_TRUCKS_REQUEST';
export const FETCH_CANS_ON_TRUCKS_SUCCESS = '@invboard/FETCH_CANS_ON_TRUCKS_SUCCESS';
export const FETCH_CANS_ON_TRUCKS_FAILURE = '@invboard/FETCH_CANS_ON_TRUCKS_FAILURE';
export const RECEIVE_CANS_ON_TRUCKS = '@invboard/RECEIVE_CANS_ON_TRUCKS';

export const FETCH_HAULS_REQUEST = '@invboard/FETCH_HAULS_REQUEST';
export const FETCH_HAULS_SUCCESS = '@invboard/FETCH_HAULS_SUCCESS';
export const FETCH_HAULS_FAILURE = '@invboard/FETCH_HAULS_FAILURE';
export const RECEIVE_HAULS = '@invboard/RECEIVE_HAULS';
