export const FETCH_DRIVER_REQUEST = '@driver/FETCH_DRIVER_REQUEST';
export const FETCH_DRIVER_SUCCESS = '@driver/FETCH_DRIVER_SUCCESS';
export const FETCH_DRIVER_FAILURE = '@driver/FETCH_DRIVER_FAILURE';
export const RECEIVE_DRIVER = '@driver/RECEIVE_DRIVER';
export const FORGET_DRIVER = '@driver/FORGET_DRIVER';

export const UPDATE_DRIVER_REQUEST = '@driver/UPDATE_DRIVER_REQUEST';
export const UPDATE_DRIVER_SUCCESS = '@driver/UPDATE_DRIVER_SUCCESS';
export const UPDATE_DRIVER_FAILURE = '@driver/UPDATE_DRIVER_FAILURE';

export const REMOVE_DRIVER_REQUEST = '@driver/REMOVE_DRIVER_REQUEST';
export const REMOVE_DRIVER_SUCCESS = '@driver/REMOVE_DRIVER_SUCCESS';
export const REMOVE_DRIVER_FAILURE = '@driver/REMOVE_DRIVER_FAILURE';

export const CREATE_DRIVER_REQUEST = '@driver/CREATE_DRIVER_REQUEST';
export const CREATE_DRIVER_SUCCESS = '@driver/CREATE_DRIVER_SUCCESS';
export const CREATE_DRIVER_FAILURE = '@driver/CREATE_DRIVER_FAILURE';
