export const AUDIT_LOG_ACTION = {
  create: 'create',
  modify: 'modify',
  delete: 'delete',
};

export const AUDIT_LOG_ENTITY = {
  promos: 'Promo',
  permits: 'Permit',
  service_areas: 'ServiceArea',
  custom_rates_groups: 'CustomRatesGroup',
  equipment_items: 'EquipmentItem',
  materials: 'Material',
  material_profiles: 'MaterialProfile',
  thresholds: 'Threshold',
  billable_surcharges: 'Surcharge',
  billable_line_items: 'LineItem',
  billable_services: 'Service',
  billable_recurring_services: 'RecurringService',
  billable_recurring_line_items: 'RecurringLineItem',
  brokers: 'Broker',
  customer_groups: 'CustomerGroup',
  '3rd_party_haulers': 'ThirdPartyHauler',
  disposal_sites: 'DisposalSite',
  business_lines: 'BusinessLine',
  business_units: 'BusinessUnit',
  companies: 'Company',
  global_rates_services: 'GeneralRackRates.Service',
  global_rates_line_items: 'GeneralRackRates.LineItem',
  // 'global_rates_recurring_line_items': 'GeneralRackRates.RecurringLineItem',
  // 'global_rates_recurring_services': 'GeneralRackRates.RecurringService',
  global_rates_thresholds: 'GeneralRackRates.Threshold',
  global_rates_surcharges: 'GeneralRackRates.Surcharge',
  disposal_site_rates: 'DisposalSiteRate',
  custom_rates_group_services: 'CustomRackRates.Service',
  custom_rates_group_line_items: 'CustomRackRates.LineItem',
  custom_rates_group_thresholds: 'CustomRackRates.Threshold',
  custom_rates_group_surcharges: 'CustomRackRates.Surcharge',
  job_sites: 'JobSite',
  customers: 'Customer',
  customer_job_site: 'CustomerJobSitePair',
  projects: 'Project',
  contacts: 'Contact',
  tax_districts: 'TaxDistrict',
  material_codes: 'MaterialCode',
  orders: 'Order',
  // 'work_orders': 'WorkOrder',
  landfill_operations: 'LandfillOperation',
  recurrent_order_templates: 'RecurrentOrderTemplate',
  drivers: 'Driver',
  truck_types: 'TruckType',
  trucks: 'Truck',
  subscription_orders: 'SubscriptionOrder',
  subscription_work_orders: 'SubscriptionOrder',
  truck_driver_general_costs: 'TruckDriverCosts',
  // 'tenants': 'Tenant', no schema detection
};

export const AUDIT_LOG_ACTIONS = Object.values(AUDIT_LOG_ACTION);

export const AUDIT_LOG_ENTITIES = Object.values(AUDIT_LOG_ENTITY);
