export default {
  billableLineItemId: 'billable_line_items',
  billableServiceId: 'billable_services',
  customerId: 'customers',
  customerGroupId: 'customer_groups',
  customerJobSiteId: 'customer_job_site',
  customRatesGroupId: 'custom_rates_groups',
  customRatesGroupThresholdsId: 'custom_rates_group_thresholds',
  customRatesGroupLineItemsId: 'custom_rates_group_line_items',
  customRatesGroupServicesId: 'custom_rates_group_services',
  customRatesGroupRecurringLineItemBillingCycleId:
    'custom_rates_group_recurring_line_item_billing_cycle',
  disposalSiteId: 'disposal_sites',
  equipmentItemId: 'equipment_items',
  globalRatesThresholdsId: 'global_rates_thresholds',
  globalRatesLineItemsId: 'global_rates_line_items',
  globalRatesServicesId: 'global_rates_services',
  globalRatesRecurringLineItemsId: 'global_rates_recurring_line_items',
  globalRatesRecurringServicesId: 'global_rates_recurring_services',
  globalRatesRecurringLineItemsBillingCycleId: 'global_rates_recurring_line_items_billing_cycle',
  jobSiteContactId: 'contacts',
  jobSiteId: 'job_sites',
  jobSite2Id: 'job_sites',
  materialId: 'materials',
  materialProfileId: 'material_profiles',
  orderContactId: 'contacts',
  permitId: 'permits',
  promoId: 'promos',
  purchaseOrderId: 'purchase_orders',
  projectId: 'projects',
  serviceFrequencyId: 'frequencies',
  subscriptionContactId: 'contacts',
  thirdPartyHaulerId: '3rd_party_haulers',
  competitorId: '3rd_party_haulers',
  thresholdId: 'thresholds',
  serviceAreaId: 'service_areas',
  surchargeId: 'billable_surcharges',
  globalRatesSurchargesId: 'global_rates_surcharges',
  customRatesGroupSurchargesId: 'custom_rates_group_surcharges',
  refactoredPriceGroupId: 'price_groups',
  originDistrictId: 'origin_districts',
};
