const CUSTOMER_COMMERCIAL_FIELDS = {
  'Reference number (unique)': 'referenceNumber',
  'Business Name': 'businessName',
  'Main Email': 'email',
  'Main Phone': 'phoneNumber',
  'Main Phone Ext (Optional)': 'phoneNumberExt',
  'Mailing Address Line 1': 'mailingAddressLine1',
  'Mailing Address Line 2 (Optional)': 'mailingAddressLine2',
  'Mailing City': 'mailingCity',
  'Mailing State': 'mailingState',
  'Mailing Zip': 'mailingZip',
  'Billing same as Mailing address': 'billingSameAsMailing',
  'Billing Address Line 1': 'billingAddressLine1',
  'Billing Address Line 2 (Optional)': 'billingAddressLine2',
  'Billing City': 'billingCity',
  'Billing State': 'billingState',
  'Billing Zip': 'billingZip',
  'Contact First Name': 'contactFirstName',
  'Contact Last Name': 'contactLastName',
  'Contact Email': 'contactEmail',
  'Contact Phone': 'contactPhone',
  'Contact Phone extension (Optional)': 'contactPhoneExt',
  'On Account': 'onAccount',
  'Terms(Required if on account)': 'paymentTerms',
  'Invoice by Type': 'invoiceByType',
  'Billing Cycle': 'billingCycle',
  'Send Invoices By Email': 'sendInvoicesByEmail',
  'Emails for invoicing': 'invoiceEmails',
  'General Notes': 'generalNote',
  'Pop up notes': 'popupNote',
};

const CUSTOMER_NON_COMMERCIAL_FIELDS = {
  'Reference number (unique)': 'referenceNumber',
  'First Name(Required if residential)': 'firstName',
  'Last Name(Required if residential)': 'lastName',
  'Business Name': 'businessName',
  'Main Email': 'email',
  'Main Phone': 'phoneNumber',
  'Main Phone Ext (Optional)': 'phoneNumberExt',
  'Mailing Address Line 1': 'mailingAddressLine1',
  'Mailing Address Line 2 (Optional)': 'mailingAddressLine2',
  'Mailing City': 'mailingCity',
  'Mailing State': 'mailingState',
  'Mailing Zip': 'mailingZip',
  'Billing same as Mailing address': 'billingSameAsMailing',
  'Billing Address Line 1': 'billingAddressLine1',
  'Billing Address Line 2 (Optional)': 'billingAddressLine2',
  'Billing City': 'billingCity',
  'Billing State': 'billingState',
  'Billing Zip': 'billingZip',
  'Contact First Name': 'contactFirstName',
  'Contact Last Name': 'contactLastName',
  'Contact Email': 'contactEmail',
  'Contact Phone': 'contactPhone',
  'Contact Phone extension (Optional)': 'contactPhoneExt',
  'On Account': 'onAccount',
  'Terms(Required if on account)': 'paymentTerms',
  'Invoice by Type': 'invoiceByType',
  'Billing Cycle': 'billingCycle',
  'Send Invoices By Email': 'sendInvoicesByEmail',
  'Emails for invoicing': 'invoiceEmails',
  'General Notes': 'generalNote',
  'Pop up notes': 'popupNote',
};

export const CUSTOMER_FIELDS_BY_GROUP_TYPE = {
  commercial: CUSTOMER_COMMERCIAL_FIELDS,
  'non-commercial': CUSTOMER_NON_COMMERCIAL_FIELDS,
};
