export const nonLinkedFields = [
  'billableServicePrice',
  'serviceDate',
  'jobSiteNote',
  'driverInstructions',
  'bestTimeToComeFrom',
  'bestTimeToComeTo',
  'someoneOnSite',
  'toRoll',
  'highPriority',
  'earlyPick',
  'invoiceNotes',
  'droppedEquipmentItem',
  'notifyDayBefore',
  'paymentMethod',
  'overrideCreditLimit',
  'csrEmail',
  'csrName',
  'callOnWayPhoneNumber',
  'callOnWayPhoneNumberId',
  'textOnWayPhoneNumber',
  'textOnWayPhoneNumberId',
  'purchaseOrderId',
  // Special case
  'businessUnitId',
  'businessLineId',
  // order requests has no HT
  'orderRequestId',
  'applySurcharges',
  'alleyPlacement',
  'cabOver',
  'commercialTaxesUsed',
  'grandTotal',
];

export const linkedFields = [
  'jobSiteId',
  'jobSite2Id',
  'customerId',
  'customerJobSiteId',
  'projectId',
  'billableServiceId',
  'equipmentItemId',
  'materialId',
  'globalRatesServicesId',
  'customRatesGroupServicesId',
  'jobSiteContactId',
  'permitId',
  'thirdPartyHaulerId',
  'orderContactId',
  'materialProfileId',
  'disposalSiteId',
  'promoId',

  'customRatesGroupId',
  // 'billableLineItemId',
  // 'globalRatesLineItemsId',
  // 'customRatesGroupLineItemsId',
  'serviceAreaId',
  'originDistrictId',
];

export const cjsPairFields = [
  'jobSiteId',
  'customerId',
  'alleyPlacement',
  'cabOver',
  'poRequired',
  'popupNote',
  'permitRequired',
  'signatureRequired',
];

export const recurrentTemplateFields = [
  'status',
  'billableLineItemsTotal',
  'billableServicePrice',
  'billableServiceTotal',
  'beforeTaxesTotal',
  'lineItems',
  'taxDistricts',
];

export const editOrderFields = [
  'id',
  'createdAt',
  'updatedAt',

  'businessUnitId',
  'businessLineId',
  'serviceAreaId',
  'status',
  'csrEmail',
  'serviceDate',

  'workOrderId',
  'independentWorkOrderId',
  'customerId',
  'jobSiteId',
  'jobSite2Id',
  'customerJobSiteId',

  'billableServiceId',
  'equipmentItemId',
  'materialId',

  'projectId',
  'jobSiteContactId',
  'permitId',
  'purchaseOrderId',
  'thirdPartyHaulerId',
  'orderContactId',
  'materialProfileId',
  'disposalSiteId',
  'customRatesGroupId',
  'promoId',
  'landfillOperationId',

  'lineItems',
  'thresholds',
  'manifestItems',

  'jobSiteNote',
  'callOnWayPhoneNumber',
  'callOnWayPhoneNumberId',
  'textOnWayPhoneNumber',
  'textOnWayPhoneNumberId',
  'driverInstructions',
  'invoiceNotes',

  'bestTimeToComeFrom',
  'bestTimeToComeTo',
  'someoneOnSite',
  'toRoll',
  'highPriority',
  'earlyPick',
  'alleyPlacement',
  'cabOver',

  'droppedEquipmentItem',
  'notifyDayBefore',

  'paymentMethod',

  'taxDistricts',

  'cancellationReasonType',
  'cancellationComment',
  'unapprovedComment',
  'unfinalizedComment',
  'rescheduleComment',
  'isRollOff',
  'applySurcharges',
  'commercialTaxesUsed',

  'priceId',
  'priceGroupId',

  'billableServicePrice',
  'billableServiceTotal',
  'billableLineItemsTotal',
  'initialGrandTotal',
  'thresholdsTotal',
  'surchargesTotal',
  'beforeTaxesTotal',
  'grandTotal',
];
