export const priceFields = [
  'id',
  'entityType',
  'billableServiceId',
  'billableLineItemId',
  'equipmentItemId',
  'materialId',
  'thresholdId',
  'surchargeId',
  'billingCycle',
  'frequencyId',
  'price',
  'nextPrice',
  'startAt',
  'endAt',
  'createdAt',
  'limit',
];
