export enum WorkOrderStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  BLOCKED = 'BLOCKED',
  CANCELED = 'CANCELED',
  COMPLETED = 'COMPLETED',
  APPROVED = 'APPROVED',
  FINALIZED = 'FINALIZED',
  INVOICED = 'INVOICED',
}
