import { createToken } from '../src/utils/serviceToken';

const main = async (): Promise<void> => {
  const token = await createToken(
    {
      userInfo: {
        id: '1fb83fcc-0829-4f15-8de9-39f6df9dbc85',
        firstName: 'Yaroslav',
        lastName: 'Porodko',
        email: 'yaroslav.porodko@eleks.com',
        resource: 'srn:starlight:recycling:1',
        permissions: [
          'recycling:Customer:list',
          'recycling:Customer:view',
          'recycling:Customer:update',
          'recycling:Customer:create',
          'recycling:Customer:delete',
          'recycling:CustomerGroup:list',
          'recycling:CustomerGroup:view',
          'recycling:CustomerGroup:update',
          'recycling:CustomerGroup:create',
          'recycling:CustomerGroup:delete',
          'recycling:CustomerTruck:list',
          'recycling:CustomerTruck:view',
          'recycling:CustomerTruck:update',
          'recycling:CustomerTruck:create',
          'recycling:CustomerTruck:delete',
          'recycling:Company:list',
          'recycling:Company:view',
          'recycling:Company:update',
          'recycling:Company:create',
          'recycling:Company:delete',
          'recycling:Container:list',
          'recycling:Container:view',
          'recycling:Container:update',
          'recycling:Container:create',
          'recycling:Container:delete',
          'recycling:Material:list',
          'recycling:Material:view',
          'recycling:Material:update',
          'recycling:Material:create',
          'recycling:Material:delete',
          'recycling:BillableItem:list',
          'recycling:BillableItem:view',
          'recycling:BillableItem:update',
          'recycling:BillableItem:create',
          'recycling:BillableItem:delete',
          'recycling:PriceGroup:list',
          'recycling:PriceGroup:view',
          'recycling:PriceGroup:update',
          'recycling:PriceGroup:create',
          'recycling:PriceGroup:delete',
          'recycling:JobSite:list',
          'recycling:JobSite:view',
          'recycling:JobSite:update',
          'recycling:JobSite:create',
          'recycling:JobSite:delete',
          'recycling:Origin:list',
          'recycling:Origin:view',
          'recycling:Origin:update',
          'recycling:Origin:create',
          'recycling:Origin:delete',
          'recycling:Destination:list',
          'recycling:Destination:view',
          'recycling:Destination:update',
          'recycling:Destination:create',
          'recycling:Destination:delete',
          'recycling:Project:list',
          'recycling:Project:view',
          'recycling:Project:update',
          'recycling:Project:create',
          'recycling:Project:delete',
          'recycling:CustomerJobSite:list',
          'recycling:CustomerJobSite:view',
          'recycling:CustomerJobSite:update',
          'recycling:CustomerJobSite:create',
          'recycling:CustomerJobSite:delete',
          'recycling:Order:list',
          'recycling:Order:view',
          'recycling:Order:update',
          'recycling:Order:create',
          'recycling:Order:delete',
          'recycling:TaxDistrict:list',
          'recycling:TaxDistrict:view',
          'recycling:TaxDistrict:update',
          'recycling:TaxDistrict:create',
          'recycling:TaxDistrict:delete',
          'recycling:CustomerContact:list',
          'recycling:CustomerContact:view',
          'recycling:CustomerContact:update',
          'recycling:CustomerContact:create',
          'recycling:CustomerContact:delete',
          'recycling:GlobalRackRates:view',
          'recycling:GlobalRackRates:update',
          'recycling:CreditCard:list',
          'recycling:CreditCard:view',
          'recycling:CreditCard:update',
          'recycling:CreditCard:create',
          'recycling:CreditCard:delete',
          'recycling:TaxExemption:list',
          'recycling:TaxExemption:view',
          'recycling:TaxExemption:update',
          'recycling:TaxExemption:create',
          'recycling:TaxExemption:delete',
          'recycling:JobSiteTaxDistrict:list',
          'recycling:JobSiteTaxDistrict:view',
          'recycling:JobSiteTaxDistrict:update',
          'recycling:JobSiteTaxDistrict:create',
          'recycling:JobSiteTaxDistrict:delete',
          'recycling:Comment:list',
          'recycling:Comment:view',
          'recycling:Comment:update',
          'recycling:Comment:create',
          'recycling:Comment:delete',
          'starlight:Role:list(platformAccount: starlight)',
          'starlight:Role:view(platformAccount: starlight)',
          'starlight:Role:update(platformAccount: starlight)',
          'starlight:Role:create(platformAccount: starlight)',
          'starlight:Role:delete(platformAccount: starlight)',
          'starlight:User:list(platformAccount: starlight)',
          'starlight:User:view(platformAccount: starlight)',
          'starlight:User:update(platformAccount: starlight)',
          'starlight:User:create(platformAccount: starlight)',
          'starlight:User:delete(platformAccount: starlight)',
        ],
      },
    },
    {
      audience: 'recycling',
      subject: '1fb83fcc-0829-4f15-8de9-39f6df9dbc85',
      requestId: 'from ctx.reqId',
    },
  );

  console.log(token);
};

main();
