import * as Joi from 'joi';
const positiveInt = Joi.number().integer().positive();
const string = Joi.string();
const date = Joi.date();

export const createSubscriptionOrder = Joi.object()
  .keys({
    billedAt: date.optional().allow(null),
    included: Joi.boolean().optional(),
    addTripCharge: Joi.boolean().optional(),
    cancellationReason: string.optional().allow(null),
    jobSiteContactId: positiveInt.optional(),
    permitId: positiveInt.optional().allow(null),
    promoId: positiveInt.optional().allow(null),
    thirdPartyHaulerId: positiveInt.optional().allow(null),
    earlyPick: Joi.boolean().optional(),
    unlockOverrides: Joi.boolean().optional(),
    workOrdersCount: Joi.number().optional(),
    status: string.optional(),
    callOnWayPhoneNumber: string.optional().allow(null),
    textOnWayPhoneNumber: string.optional().allow(null),
    alleyPlacement: Joi.boolean().optional(),
    toRoll: Joi.boolean().optional(),
    subscriptionContactId: positiveInt.optional(),
    signatureRequired: Joi.boolean().optional(),
    canReschedule: Joi.boolean().optional(),
    oneTime: Joi.boolean().optional(),
    instructionsForDriver: string.optional().allow(null),
    jobSiteNote: string.optional().allow(null),
    onejobSiteContactTextOnlytime: Joi.boolean().optional(),
    bestTimeToComeFrom: string.optional().allow(null),
    bestTimeToComeTo: string.optional().allow(null),
    someoneOnSite: Joi.boolean().optional(),
    highPriority: Joi.boolean().optional(),
    hasComments: Joi.boolean().optional().allow(null),
    hasAssignedRoutes: Joi.boolean().optional().allow(null),
    startedAt: date.optional().allow(null),
    canceledAt: date.optional().allow(null),
    completedAt: date.optional().allow(null),
    poRequired: Joi.boolean().optional(),
    permitRequired: Joi.boolean().optional(),
    subscriptionServiceItemId: positiveInt.required(),
    billableServiceId: positiveInt.optional(),
    materialId: positiveInt.optional(),
    globalRatesServicesId: positiveInt.optional().allow(null),
    customRatesGroupServicesId: positiveInt.optional().allow(null),
    serviceDate: date.required(),
    price: Joi.number().optional().allow(0),
    quantity: positiveInt.optional(),
    grandTotal: Joi.number().optional().allow(0),
    serviceDayOfWeekRequiredByCustomer: Joi.boolean().optional().allow(null),
    assignedRoute: string.optional().allow(null),
    billableLineItemsTotal: Joi.number().optional(),
    cancellationComment: string.optional().allow(null),
    overrideCreditLimit: Joi.boolean().optional(),
    invoicedDate: date.optional().allow(null),
    arrivedAt: date.optional().allow(null),
    deletedAt: date.optional().allow(null),
    customRatesGroupId: positiveInt.optional().allow(null).allow(0),
    destinationJobSiteId: positiveInt.optional().allow(null),
    subscriptionId: positiveInt.required(),
    sequenceId: string.required(),
    purchaseOrderId: positiveInt.optional().allow(null),
    applySurcharges: Joi.boolean().optional(),
    isFinalForService: Joi.boolean().optional(),
    // refactor starts here
    surchargesTotal: Joi.number().optional().allow(null),
    beforeTaxesTotal: Joi.number().optional().allow(null),
    invoicedAt: date.optional().allow(null),
    paidAt: date.optional().allow(null),
    priceId: positiveInt.optional().allow(null),
    priceGroupHistoricalId: positiveInt.optional().allow(null),
    //end
    createdAt: date.optional(),
    updatedAt: date.optional(),
    invoiceNotes: string.optional().allow(null),
    uncompletedComment: string.optional().allow(null),
    unapprovedComment: string.optional().allow(null),
    unfinalizedComment: string.optional().allow(null),
    droppedEquipmentItem: string.optional().allow(null),
    pickedUpEquipmentItem: string.optional().allow(null),
    weight: Joi.number().optional().allow(null),
    finishWorkOrderDate: date.optional().allow(null),
    weightUnit: string.optional().allow(null),
  })
  .required();

export const bulkCreateSubscriptionOrder = Joi.object().keys({
  data: Joi.array().items(createSubscriptionOrder),
});

export const updateSubscriptionOrder = Joi.object()
  .keys({
    billedAt: date.optional().allow(null),
    included: Joi.boolean().optional(),
    addTripCharge: Joi.boolean().optional(),
    cancellationReason: string.optional(),
    jobSiteContactId: positiveInt.optional(),
    permitId: positiveInt.optional().allow(null),
    promoId: positiveInt.optional().allow(null),
    thirdPartyHaulerId: positiveInt.optional().allow(null),
    earlyPick: Joi.boolean().optional(),
    unlockOverrides: Joi.boolean().optional(),
    workOrdersCount: Joi.number().optional(),
    status: string.optional(),
    callOnWayPhoneNumber: string.optional().allow(null),
    textOnWayPhoneNumber: string.optional().allow(null),
    alleyPlacement: Joi.boolean().optional(),
    toRoll: Joi.boolean().optional(),
    subscriptionContactId: positiveInt.optional(),
    signatureRequired: Joi.boolean().optional(),
    canReschedule: Joi.boolean().optional(),
    oneTime: Joi.boolean().optional(),
    instructionsForDriver: string.optional().allow(null),
    jobSiteNote: string.optional().allow(null),
    onejobSiteContactTextOnlytime: Joi.boolean().optional(),
    bestTimeToComeFrom: string.optional().allow(null),
    bestTimeToComeTo: string.optional().allow(null),
    someoneOnSite: Joi.boolean().optional(),
    highPriority: Joi.boolean().optional(),
    hasComments: Joi.boolean().optional(),
    hasAssignedRoutes: Joi.boolean().optional(),
    startedAt: date.optional(),
    canceledAt: date.optional(),
    completedAt: date.optional(),
    poRequired: Joi.boolean().optional(),
    permitRequired: Joi.boolean().optional(),
    subscriptionServiceItemId: positiveInt.optional(),
    billableServiceId: positiveInt.optional(),
    materialId: positiveInt.optional(),
    globalRatesServicesId: positiveInt.optional().allow(null),
    customRatesGroupServicesId: positiveInt.optional().allow(null),
    serviceDate: date.optional(),
    price: Joi.number().optional().allow(0),
    quantity: positiveInt.optional(),
    grandTotal: Joi.number().optional().allow(0),
    serviceDayOfWeekRequiredByCustomer: Joi.boolean().optional().allow(null),
    assignedRoute: string.optional().allow(null),
    billableLineItemsTotal: Joi.number().optional().allow(0),
    cancellationComment: string.optional().allow(null),
    overrideCreditLimit: Joi.boolean().optional(),
    invoicedDate: date.optional(),
    arrivedAt: date.optional(),
    deletedAt: date.optional(),
    customRatesGroupId: positiveInt.optional().allow(null),
    destinationJobSiteId: positiveInt.optional().allow(null),
    subscriptionId: positiveInt.optional(),
    sequenceId: string.optional(),
    purchaseOrderId: positiveInt.optional().allow(null),
    applySurcharges: Joi.boolean().optional(),
    isFinalForService: Joi.boolean().optional(),
    // refactor starts here
    surchargesTotal: Joi.number().optional(),
    beforeTaxesTotal: Joi.number().optional(),
    invoicedAt: date.optional(),
    paidAt: date.optional(),
    priceId: positiveInt.optional(),
    priceGroupHistoricalId: positiveInt.optional(),
    //end
    createdAt: date.optional(),
    updatedAt: date.optional(),
    invoiceNotes: string.optional().allow(null),
    uncompletedComment: string.optional().allow(''),
    unapprovedComment: string.optional().allow(''),
    unfinalizedComment: string.optional().allow(''),
    droppedEquipmentItem: string.optional().allow(null),
    pickedUpEquipmentItem: string.optional().allow(null),
    weight: Joi.number().optional().allow(null).allow(null),
    finishWorkOrderDate: date.optional().allow(null),
    weightUnit: string.optional().allow(null),
  })
  .required();
